version: '3.8'
services:
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "26379:6379"
    container_name : redis
    networks:
      - vehicle
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  database:
    image: 'postgres:15.2'
    ports:
      - '25432:5432'
    container_name : database
    networks:
      - vehicle
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
networks:
  vehicle:
